### ISSUE TITLE
Steer Zwift handshake broken in latest Zwift versions

### ISSUE THREAD

**Issue by vincent290587** [fiveohhh/zwift-steerer#2]
Hi !

And congrats on the super nice reverse engineering work ;-)

I noticed the compatibility with Zwift broke a few months ago, are you still keeping that repo updated ?

I just ordered a Sterzo to try and help figuring out what is wrong

**Comment by fiveohhh** [comment]
Zwift decided to change the protocol.  At this point I don't have any interest in trying to figure it out, but let me know if you do and I'll gladly update things.
